const router = {
    'Main': require('../'),
    'ViewPage': require('../pages/ViewPage'),
    'TextPage': require('../pages/TextPage'),
    'TextInputPage': require('../pages/TextInputPage'),
    'ButtonPage': require('../pages/ButtonPage'),
    'TouchablePage': require('../pages/TouchablePage'),
    'IconPage': require('../pages/IconPage'),
    'DividerPage': require('../pages/DividerPage'),
    'LabelPage': require('../pages/LabelPage'),
    'ToolbarPage': require('../pages/ToolbarPage'),
    'ListItemPage': require('../pages/ListItemPage'),
    'ModalPage': require('../pages/ModalPage'),
    'CardPage': require('../pages/CardPage'),
    'AvatarPage': require('../pages/AvatarPage'),
    'TooltipPage': require('../pages/TooltipPage'),
    'ToastPage': require('../pages/ToastPage'),
    'ARTPage': require('../pages/ARTPage'),
    'SVGPage': require('../pages/SVGPage'),
    'StoragePage': require('../pages/StoragePage'),
    'AnimatedPage': require('../pages/AnimatedPage'),
    'ListViewPage': require('../pages/ListViewPage'),
    'FlatListPage': require('../pages/FlatListPage'),
    'SwipePage': require('../pages/SwipePage'),
    'UltimateListPage': require('../pages/UltimateListPage'),
    'VRVideoPage': require('../pages/VRVideoPage'),
    'DimensPage': require('../pages/DimensPage'),

}
export default router;